micronaut:
  application:
    name: server
  server:
    port: 6969
    cors:
      enabled: true
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:public"
mongodb:
  uri:  "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"

grails:
  mongodb:
    engine: codec
    databaseName: 'vidly'
