export const RUBY_FETCH_MOVIE_LIST = process.env.REACT_APP_APPLICATION_SERVER_URL + "/api/v1/movie"
export const SCORE_CARD_FETCH_COURSE_INFO = process.env.REACT_APP_APPLICATION_SERVER_URL + "CREATE API"
